services:
  postgres:
    image: postgres:latest
    container_name: systemload-postgres
    environment:
      POSTGRES_DB: systemload
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d systemload"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - systemload-network

  # pgAdmin (Optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: systemload-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@systemload.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - systemload-network

  # Redis (for caching - optional)
  # redis:
  #   image: redis:7-alpine
  #   container_name: systemload-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   networks:
  #     - systemload-network

volumes:
  postgres_data:
  pgadmin_data:
  # redis_data:

networks:
  systemload-network:
    driver: bridge
