services:
  ml_models:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: system-load-ml-models
    ports:
      - "8010:8010"
    volumes:
      - ../data:/app/data
      - ./scripts:/app/scripts
      - ./main.py:/app/main.py
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
