server:
  port: 8080

spring:
  application:
    name: system-load-ai

  # Database Configuration
  datasource:
    url: jdbc:postgresql://postgres:5432/system_load_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Redis Configuration
  redis:
    host: redis
    port: 6379

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    com.systemload: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
